### create a user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Pratt6",
    "email": "prasanna6@technital.it"
}

### get all users
GET http://localhost:3000/api/users

### get a user
GET http://localhost:3000/api/users/6

### update a user
PUT http://localhost:3000/api/users/7
Content-Type: application/json

{
    "name": "Prasana",
    "email": "prasanna12@technital.it"
}

### delete a user
DELETE http://localhost:3000/api/users/3




### get all products
GET http://localhost:3000/api/products

### create a product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Milk",
    "price": 1.5
}

### create a product
POST http://localhost:3000/api/products
Content-Type: application/json

{
    "name": "Apple",
    "price": 0.5
}



### get all events
GET http://localhost:3000/api/events

### create a product
POST http://localhost:3000/api/events
Content-Type: application/json

{
    "name": "Steve Birthday",
    "content": "Party at Lotte Hotel"
}

### create a product
POST http://localhost:3000/api/events
Content-Type: application/json

{
    "name": "App launching",
    "content": "Media Conference Call"
}